source 'https://github.com/cocoapods/specs.git'

use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!


target 'IdentanceExample' do
	pod 'Down', '0.9.2'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "Down"
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = "YES"
      end
    end
  end
end
